

export const LINK_CHECKER_START="LINK_CHECKER_START";
export const LINK_CHECKER_SUCCESS="LINK_CHECKER_SUCCESS";
export const LINK_CHECKER_FAIL="LINK_CHECKER_FAIL";


export const SET_ICON_START="SET_ICON_START";
export const SET_ICON_SUCCESS="SET_ICON_SUCCESS";
export const SET_ICON_FAIL="SET_ICON_FAIL";


export const GET_ICON_START="GET_ICON_START";
export const GET_ICON_SUCCESS="GET_ICON_SUCCESS";
export const GET_ICON_FAIL="GET_ICON_FAIL";


export const DELETE_LINK_START="DELETE_LINK_START";
export const DELETE_LINK_SUCCESS="DELETE_LINK_SUCCESS";
export const DELETE_LINK_FAIL="DELETE_LINK_FAIL";


export const UPDATE_LINK_START="UPDATE_LINK_START";
export const UPDATE_LINK_SUCCESS="UPDATE_LINK_SUCCESS";
export const UPDATE_LINK_FAIL="UPDATE_LINK_FAIL";

export const ABOVE_LINK_START="ABOVE_LINK_START";
export const ABOVE_LINK_SUCCESS="ABOVE_LINK_SUCCESS";
export const ABOVE_LINK_FAIL="ABOVE_LINK_FAIL";

export const GET_PUBLIC_LINK_START="GET_PUBLIC_LINK_START";
export const GET_PUBLIC_LINK_SUCCESS="GET_PUBLIC_LINK_SUCCESS";
export const GET_PUBLIC_LINK_FAIL="GET_PUBLIC_LINK_FAIL";

export const EDIT_PROFILE_START="EDIT_PROFILE_START";
export const EDIT_PROFILE_SUCCESS="EDIT_PROFILE_SUCCESS";
export const EDIT_PROFILE_FAIL="EDIT_PROFILE_FAIL";

export const ENB_SHARE_BTN_START="ENB_SHARE_BTN_START";
export const ENB_SHARE_BTN_SUCCESS="ENB_SHARE_BTN_SUCCESS";
export const ENB_SHARE_BTN_FAIL="ENB_SHARE_BTN_FAIL";

export const SET_VIDEO_START="SET_VIDEO_START";
export const SET_VIDEO_SUCCESS="SET_VIDEO_SUCCESS";
export const SET_VIDEO_FAIL="SET_VIDEO_FAIL";

export const SET_FAV_START="SET_FAV_START";
export const SET_FAV_SUCCESS="SET_FAV_SUCCESS";
export const SET_FAV_FAIL="SET_FAV_FAIL";

export const SET_PAGE_TITLES_START="SET_PAGE_TITLES_START";
export const SET_PAGE_TITLES_SUCCESS="SET_PAGE_TITLES_SUCCESS";
export const SET_PAGE_TITLES_FAIL="SET_PAGE_TITLES_FAIL";

export const SET_LAYOUT_START="SET_LAYOUT_START";
export const SET_LAYOUT_SUCCESS="SET_LAYOUT_SUCCESS";
export const SET_LAYOUT_FAIL="SET_LAYOUT_FAIL";









